baseURL: 'https://jhxs.github.io/' # ç»‘å®šçš„åŸŸå
title: 'hansel çš„åƒåœ¾ç«™'
theme: 'PaperMod'  # ä¸»é¢˜åç§°ï¼Œå’Œthemesæ–‡ä»¶å¤¹ä¸‹çš„ä¸€è‡´
languageCode: zh-cn # en-us
pagination:
  pagerSize: 10 # é¦–é¡µæ–‡ç« æ˜¾ç¤ºä¸ªæ•°
# summaryLength: 999999 # é¦–é¡µæ–‡ç« æ‘˜è¦å­—æ•°
enableGitInfo: true        # æŠŠ git æäº¤æ—¶é—´å½“ä½œ lastmod

hasCJKLanguage: true # è‡ªåŠ¨æ£€æµ‹æ˜¯å¦åŒ…å«ä¸­æ–‡æ—¥æ–‡éŸ©æ–‡,å¦‚æœæ–‡ç« ä¸­ä½¿ç”¨äº†å¾ˆå¤šä¸­æ–‡å¼•å·çš„è¯å¯ä»¥å¼€å¯
enableInlineShortcodes: true
enableEmoji: true # å…è®¸ä½¿ç”¨ Emoji è¡¨æƒ…ï¼Œå»ºè®® true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

defaultContentLanguage: zh # æœ€é¡¶éƒ¨é¦–å…ˆå±•ç¤ºçš„è¯­è¨€é¡µé¢
defaultContentLanguageInSubdir: false # URL ä¸­æ˜¯å¦æ˜¾ç¤ºè¯­è¨€ä»£ç 

languages:
    zh:
      languageName: "ä¸­æ–‡"
      # contentDir: content/english
      languageCode: zh-cn
      weight: 1

menu:
  main:
    - name: "ğŸ“šæ–‡ç« "
      url: "/posts"
      weight: 1
    - name: "âœæ—¥è®°"
      url: "/journal"
      weight: 2    
    - name: "â±æ—¶é—´è½´"
      url: "/archives"
      weight: 3
    - name: "ğŸ·ï¸æ ‡ç­¾"
      url: "/tags"
      weight: 4
    - name: "ğŸ”æœç´¢"
      url: "/search/"
      weight: 5

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  homeInfoParams:
    Title: "ä½ å¥½ï¼Œæˆ‘æ˜¯ hansel "
    Content: "æ¬¢è¿æ¥åˆ°æˆ‘çš„åšå®¢ä¸»é¡µ "

  showtoc: true   # è®©æ–‡ç« é¡µå‡ºç°ç›®å½•
  TocOpen: true # è‡ªåŠ¨å±•å¼€ç›®å½•

  DateFormat: "2006å¹´01æœˆ02æ—¥"
  defaultTheme: "auto"
  disableThemeToggle: false # æ˜¯å¦ç¦ç”¨ä¸»é¢˜åˆ‡æ¢æŒ‰é’®
  # ShowShareButtons: true # æ˜¾ç¤ºç¤¾äº¤åˆ†äº«æŒ‰é’®
  # ShowReadingTime: true # æ˜¾ç¤ºé˜…è¯»æ—¶é—´
  # disableSpecialistPost: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  hideFooter: false # éšè—é¡µè„š
  ShowWordCount: true
  lazyLoad: true # å›¾ç‰‡æ‡’åŠ è½½

  ShowLastMod: true #æ˜¾ç¤ºæ–‡ç« æ›´æ–°æ—¶é—´

  comments: true # æ˜¯å¦å¯ç”¨è¯„è®ºåŠŸèƒ½
  

markup:
    goldmark:
        renderer:
            unsafe: true # HUGO é»˜è®¤è½¬ä¹‰ Markdown æ–‡ä»¶ä¸­çš„ HTML ä»£ç ï¼Œå¦‚éœ€å¼€å¯çš„è¯
    highlight:
        # anchorLineNos: true
        codeFences: true # å¯ç”¨ä»£ç å›´æ é«˜äº®
        guessSyntax: true # è‡ªåŠ¨çŒœæµ‹ä»£ç è¯­è¨€
        lineNos: true  # æ˜¾ç¤ºè¡Œå·
        noClasses: false # ä½¿ç”¨ CSS class æ§åˆ¶æ ·å¼ï¼ˆæ–°ç‰ˆæ¨èå†™æ³•ï¼‰
        # style: monokai
        style: darcula # ä»£ç é«˜äº®ä¸»é¢˜
